name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      - name: Notify Discord
        uses: bbelderbos/discord-webhook@v1
        with:
          url: https://discord.com/api/webhooks/1270103464952991815/hmINYcSFAj0eZGESK6ViPXRYZFdBOUOsBIKJjk3o68pUte6tY4xrVc64d8CuCQQztwzc
          content: |
            **New Commit on ${{ github.repository }}**
            - **Author:** ${{ github.actor }}
            - **Commit Message:** ${{ github.event.head_commit.message }}
            - **Commit URL:** ${{ github.event.head_commit.url }}
